{{ if .Values.opentelemetryOperator.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-jaeger
  namespace: {{ template "tobs.namespace" . }}
  labels:
    app: {{ template "tobs.fullname" . }}
    chart: {{ template "tobs.chart" . }}
    release: {{ .Release.Name }}
    component: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "tobs.fullname" . }}
      component: jaeger
  template:
    metadata:
      labels:
        app: {{ template "tobs.fullname" . }}
        component: jaeger
    spec:
      containers:
        - image: {{ .Values.opentelemetryOperator.jaeger.image }}
          imagePullPolicy: IfNotPresent
          name: jaeger
          {{- if .Values.opentelemetryOperator.jaeger.args }}
          args:
            {{- range $key := .Values.opentelemetryOperator.jaeger.args }}
              - {{ tpl $key $ }}
            {{- end }}
          {{- end }}
          {{- if .Values.opentelemetryOperator.jaeger.resources }}
          resources:
            {{- toYaml .Values.opentelemetryOperator.jaeger.resources | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 16686
              name: jaeger-ui
          env:
            {{- toYaml .Values.opentelemetryOperator.jaeger.env | nindent 12 }}
          {{- with .Values.opentelemetryOperator.jaeger.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.opentelemetryOperator.jaeger.tolerations }}
          tolerations: {{ toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.opentelemetryOperator.jaeger.affinity }}
          affinity: {{ toYaml . | nindent 8 }}
          {{- end }}
{{- end -}}